services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advcredito_app
    ports:
      - "3000:3000"
      - "3004:3004"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: advcredito_db
    environment:
      - POSTGRES_USER=advuser
      - POSTGRES_PASSWORD=advpassword
      - POSTGRES_DB=advdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

